class CareGuideStrings {
  const CareGuideStrings(this.language);
  final String language;
  String get _code => language == 'Kannada' || language == 'kn' ? 'kn' : language == 'Hindi' || language == 'hi' ? 'hi' : 'en';
  String t(String key) => (_values[_code]?[key] ?? _values['en']![key] ?? key);
  static const _values = {
    'en': {'assistant':'Hospital resource assistant','newChat':'New conversation','language':'Language','nearby':'Find nearby hospitals','bookHelp':'How do I book an appointment?','ambulance':'I need an ambulance','blood':'Check blood availability','locationOn':'Location is active for nearby recommendations','locationOff':'Enable location for nearby recommendations','locationLoading':'Getting your location...','locationDisabled':'Location services are turned off. Please enable location services.','locationPermission':'Location permission is required to find hospitals near you.','locationPermanent':'Location permission is permanently denied. Enable it in app settings.','locationError':'Unable to determine your current location. Please try again.','refreshLocation':'Refresh location','openSettings':'Open settings','enable':'Enable','viewHospital':'View hospital details','useLocation':'Use my location','view':'View Hospital','book':'Book Appointment','directions':'Directions','call':'Call hospital','sos':'Emergency SOS','typing':'CareGuide is thinking…','placeholder':'Ask about care, appointments, or resources','beds':'Beds','ventilators':'Ventilators','kmAway':'km away','addressUnavailable':'Address unavailable','unavailable':'The AI assistant is temporarily unavailable. Please try again.','failed':'I could not complete that request. Please try again.','newStarted':'New conversation started. How can I help?','welcome':'Hello! I am CareGuide, your hospital resource assistant. I can help you find nearby care, understand services, and navigate urgent requests.'},
    'kn': {'assistant':'ಆಸ್ಪತ್ರೆ ಸಂಪನ್ಮೂಲ ಸಹಾಯಕ','newChat':'ಹೊಸ ಸಂಭಾಷಣೆ','language':'ಭಾಷೆ','nearby':'ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗಳನ್ನು ಹುಡುಕಿ','bookHelp':'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಅನ್ನು ಹೇಗೆ ಬುಕ್ ಮಾಡುವುದು?','ambulance':'ನನಗೆ ಆಂಬ್ಯುಲೆನ್ಸ್ ಬೇಕು','blood':'ರಕ್ತದ ಲಭ್ಯತೆಯನ್ನು ಪರಿಶೀಲಿಸಿ','locationOn':'ಹತ್ತಿರದ ಶಿಫಾರಸುಗಳಿಗೆ ಸ್ಥಳ ಸಕ್ರಿಯವಾಗಿದೆ','locationOff':'ಹತ್ತಿರದ ಶಿಫಾರಸುಗಳಿಗಾಗಿ ಸ್ಥಳ ಸಕ್ರಿಯಗೊಳಿಸಿ','locationLoading':'ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ಪಡೆಯಲಾಗುತ್ತಿದೆ...','locationDisabled':'ಸ್ಥಳ ಸೇವೆಗಳು ಆಫ್ ಆಗಿವೆ. ದಯವಿಟ್ಟು ಸ್ಥಳ ಸೇವೆಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ.','locationPermission':'ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗಳನ್ನು ಹುಡುಕಲು ಸ್ಥಳ ಅನುಮತಿ ಅಗತ್ಯವಿದೆ.','locationPermanent':'ಸ್ಥಳ ಅನುಮತಿಯನ್ನು ಅಪ್ಲಿಕೇಶನ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ಸಕ್ರಿಯಗೊಳಿಸಿ.','locationError':'ನಿಮ್ಮ ಪ್ರಸ್ತುತ ಸ್ಥಳವನ್ನು ಕಂಡುಹಿಡಿಯಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.','refreshLocation':'ಸ್ಥಳವನ್ನು ನವೀಕರಿಸಿ','openSettings':'ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ತೆರೆಯಿರಿ','enable':'ಸಕ್ರಿಯಗೊಳಿಸಿ','viewHospital':'ಆಸ್ಪತ್ರೆಯ ವಿವರಗಳನ್ನು ನೋಡಿ','useLocation':'ನನ್ನ ಸ್ಥಳವನ್ನು ಬಳಸಿ','view':'ಆಸ್ಪತ್ರೆ ನೋಡಿ','book':'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್ ಮಾಡಿ','directions':'ದಿಕ್ಕುಗಳು','call':'ಕರೆ ಮಾಡಿ','sos':'ತುರ್ತು ಸಹಾಯ','typing':'ಕೇರ್‌ಗೈಡ್ ಯೋಚಿಸುತ್ತಿದೆ…','placeholder':'ಆರೈಕೆ, ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಅಥವಾ ಸಂಪನ್ಮೂಲಗಳ ಬಗ್ಗೆ ಕೇಳಿ','beds':'ಹಾಸಿಗೆಗಳು','ventilators':'ವೆಂಟಿಲೇಟರ್‌ಗಳು','kmAway':'ಕಿ.ಮೀ ದೂರ','addressUnavailable':'ವಿಳಾಸ ಲಭ್ಯವಿಲ್ಲ','unavailable':'AI ಸಹಾಯಕ ಈಗ ಲಭ್ಯವಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.','failed':'ನಿಮ್ಮ ವಿನಂತಿಯನ್ನು ಪೂರ್ಣಗೊಳಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.','newStarted':'ಹೊಸ ಸಂಭಾಷಣೆ ಪ್ರಾರಂಭವಾಗಿದೆ. ನಾನು ಹೇಗೆ ಸಹಾಯ ಮಾಡಲಿ?','welcome':'ನಮಸ್ಕಾರ! ನಾನು ಕೇರ್‌ಗೈಡ್, ನಿಮ್ಮ ಆಸ್ಪತ್ರೆ ಸಂಪನ್ಮೂಲ ಸಹಾಯಕ. ಹತ್ತಿರದ ಆರೈಕೆ, ಸೇವೆಗಳು ಮತ್ತು ತುರ್ತು ಸಹಾಯದಲ್ಲಿ ನೆರವಾಗಬಹುದು.'},
    'hi': {'assistant':'अस्पताल संसाधन सहायक','newChat':'नई बातचीत','language':'भाषा','nearby':'नजदीकी अस्पताल खोजें','bookHelp':'अपॉइंटमेंट कैसे बुक करें?','ambulance':'मुझे एम्बुलेंस चाहिए','blood':'रक्त की उपलब्धता देखें','locationOn':'नजदीकी सुझावों के लिए स्थान सक्रिय है','locationOff':'नजदीकी सुझावों के लिए स्थान सक्षम करें','locationLoading':'आपका स्थान प्राप्त किया जा रहा है...','locationDisabled':'स्थान सेवाएं बंद हैं। कृपया उन्हें चालू करें।','locationPermission':'आपके पास के अस्पताल खोजने के लिए स्थान अनुमति आवश्यक है।','locationPermanent':'ऐप सेटिंग में स्थान अनुमति सक्षम करें।','locationError':'आपका वर्तमान स्थान निर्धारित नहीं किया जा सका।','refreshLocation':'स्थान रीफ़्रेश करें','openSettings':'सेटिंग खोलें','enable':'सक्षम करें','viewHospital':'अस्पताल का विवरण देखें','useLocation':'मेरा स्थान उपयोग करें','view':'अस्पताल देखें','book':'अपॉइंटमेंट बुक करें','directions':'दिशा-निर्देश','call':'कॉल करें','sos':'आपातकालीन सहायता','typing':'केयरगाइड सोच रहा है…','placeholder':'देखभाल, अपॉइंटमेंट या संसाधनों के बारे में पूछें','beds':'बेड','ventilators':'वेंटिलेटर','kmAway':'किमी दूर','addressUnavailable':'पता उपलब्ध नहीं','unavailable':'AI सहायक अभी उपलब्ध नहीं है। कृपया फिर प्रयास करें।','failed':'आपका अनुरोध पूरा नहीं किया जा सका। कृपया फिर प्रयास करें।','newStarted':'नई बातचीत शुरू हुई। मैं कैसे मदद करूँ?','welcome':'नमस्ते! मैं केयरगाइड, आपका अस्पताल संसाधन सहायक हूँ। मैं नजदीकी देखभाल, सेवाओं और आपात सहायता में मदद कर सकता हूँ.'},
  };
}
