const router = require('express').Router();
const medical = require('../controllers/medicalController');
const { protect, authorize } = require('../middleware/auth');
router.use(protect);
router.get('/onboarding-status', authorize('patient'), medical.getOnboarding);
router.put('/profile', authorize('patient'), medical.saveProfile);
router.post('/records', medical.createRecord);
router.get('/health-records/:recordId', medical.getRecord);
router.put('/health-records/:recordId', medical.updateRecord);
router.delete('/health-records/:recordId', medical.removeRecord);
router.put('/records/:recordId/verify', authorize('staff'), medical.verifyRecord);
router.get('/patients/:id/profile', medical.resolvePatient, medical.getProfile);
router.get('/patients/:id/timeline', medical.resolvePatient, medical.getTimeline);
router.get('/patients/:id/medical-profile', medical.resolvePatient, medical.getProfile);
router.put('/patients/:id/medical-profile', authorize('patient'), medical.resolvePatient, medical.saveProfile);
router.post('/patients/:id/medical-history', authorize('patient'), medical.resolvePatient, medical.createRecord);
router.get('/patients/:id/medical-history', medical.resolvePatient, medical.getTimeline);
router.post('/patients/:id/medical-documents', authorize('patient'), medical.resolvePatient, medical.createRecord);
router.get('/patients/:id/medical-documents', medical.resolvePatient, medical.getTimeline);
router.get('/patients/:id/health-records', medical.resolvePatient, medical.getTimeline);
router.post('/patients/:id/health-records', authorize('patient'), medical.resolvePatient, medical.createRecord);
router.get('/appointments/:appointmentId/patient-summary', medical.getAppointmentSummary);
router.get('/appointments/:appointmentId/patient-history', medical.getAppointmentHistory);
router.post('/consultations', medical.createConsultation);
router.post('/prescriptions', medical.createPrescription);
module.exports = router;
